# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- test
- test/*

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -e .
    pip install pytest==4.5
    pip install pytest-cov==2.7.1
    pip install pylint-fail-under==0.2.0
    pip install wheel
  displayName: 'Install dependencies'

- script: |
    pytest --cov=uitestcore --cov-fail-under=95 --cov-report term-missing --junitxml='reports/junit/unit-tests.xml'
  displayName: 'Unit tests with coverage'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'reports/junit/unit-tests.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- script: |
    pylint-fail-under --fail_under 9.5 uitestcore
  displayName: 'Pylint'

- script: python setup.py sdist bdist_wheel
  displayName: 'Build sdist'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/dist
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dist'